services:
  - type: web
    name: trdgwdbot-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: trdgwdbot
      - key: DERIV_DEFAULT_APP_ID
        value: 1089
      - key: FERNET_KEY
        generateValue: true
      - key: API_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        sync: false
